using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using IntegratoR.Abstractions.Domain.Entities;
using IntegratoR.OData.Common.Annotations;
using IntegratoR.OData.FO.Domain.Enums.General;
using IntegratoR.OData.FO.Domain.Enums.LedgerJournals;

namespace IntegratoR.OData.FO.Domain.Entities.LedgerJournal;

/// <summary>
/// Represents the header of a general journal in D365 F&amp;O, mapping to the <c>LedgerJournalHeader</c> data entity, and acts as the container for a batch of journal lines.
/// </summary>
[Table("LedgerJournalHeaders")]
public class LedgerJournalHeader : BaseEntity
{
    /// <summary>
    /// Gets or sets the legal entity (company) in which the journal is created. Part of the composite key.
    /// </summary>
    [Key]
    [JsonPropertyName("dataAreaId")]
    [ODataField(IsRequired = true)]
    public required string DataAreaId { get; set; }

    /// <summary>
    /// Gets or sets the journal batch number, generated by a D365 F&amp;O number sequence on create. Part of the composite key.
    /// </summary>
    [Key]
    [JsonPropertyName("JournalBatchNumber")]
    [ODataField(IgnoreOnCreate = true)]
    public string? JournalBatchNumber { get; set; }

    /// <summary>
    /// Gets or sets the journal name setup that governs the journal's default values, number sequences, and posting restrictions.
    /// </summary>
    /// <remarks>Read-only after create; D365 rejects updating it with an <c>ODataSecurityException</c>, so it is excluded from the update payload.</remarks>
    [JsonPropertyName("JournalName")]
    [ODataField(IgnoreOnUpdate = true)]
    public virtual required string JournalName { get; set; }

    /// <summary>
    /// Gets or sets a user-defined description for the journal batch.
    /// </summary>
    [JsonPropertyName("Description")]
    public virtual required string Description { get; set; }

    /// <summary>
    /// Gets or sets a unique identifier from an external system, used for tracking and idempotency in integration scenarios.
    /// </summary>
    [JsonPropertyName("IntegrationKey")]
    public virtual string? IntegrationKey { get; set; }

    /// <summary>
    /// Gets or sets the financial posting layer for the journal's transactions.
    /// </summary>
    [JsonPropertyName("PostingLayer")]
    public virtual CurrentOperationsTax PostingLayer { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the journal has been posted to the general ledger. Read-only in D365.
    /// </summary>
    [JsonPropertyName("IsPosted")]
    [ODataField(IgnoreOnUpdate = true)]
    public virtual NoYes IsPosted { get; set; }

    /// <summary>
    /// Gets or sets the system-calculated total of all debit amounts from the journal lines. Read-only in D365.
    /// </summary>
    [JsonPropertyName("JournalTotalDebit")]
    [ODataField(IgnoreOnUpdate = true)]
    public virtual decimal JournalTotalDebit { get; set; }

    /// <summary>
    /// Gets or sets the system-calculated total of all credit amounts from the journal lines. Read-only in D365.
    /// </summary>
    [JsonPropertyName("JournalTotalCredit")]
    [ODataField(IgnoreOnUpdate = true)]
    public virtual decimal JournalTotalCredit { get; set; }

    /// <summary>
    /// Gets or sets the accounting currency of the legal entity.
    /// </summary>
    /// <remarks>Read-only in D365; updating it is rejected with an <c>ODataSecurityException</c>, so it is excluded from the update payload.</remarks>
    [JsonPropertyName("AccountingCurrency")]
    [ODataField(IgnoreOnUpdate = true)]
    public virtual string? AccountingCurrency { get; set; }

    /// <summary>
    /// Gets the composite key formed from <see cref="DataAreaId"/> and <see cref="JournalBatchNumber"/>.
    /// </summary>
    public override object[] GetCompositeKey()
    {
        // null-forgiving: a null JournalBatchNumber flows through as a real null element (NOT the
        // literal "null"); ODataService.BuildCompositeKeyObject turns that into a Validation failure.
        // The ! suppresses CS8601 since the array is object[] but the property is string?.
        return [DataAreaId, JournalBatchNumber!];
    }
}
