<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.DurableTask.Abstractions" />
    <PackageReference Include="Microsoft.DurableTask.Worker" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntegratoR.Application\IntegratoR.Application.csproj" />
    <ProjectReference Include="..\IntegratoR.OData.FO\IntegratoR.OData.FO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IntegratoR.Hosting.Tests" />
  </ItemGroup>

</Project>
