using System.Globalization;
using System.Text;
using IntegratoR.CodeGen.Models;

namespace IntegratoR.CodeGen.Services;

/// <summary>
/// Generates C# entity source files from parsed CSDL models.
/// Produces partial classes inheriting from <c>BaseEntity&lt;string&gt;</c> with full
/// OData attribute decoration matching D365 F&amp;O metadata.
/// </summary>
public class EntityGenerator
{
    private const string DefaultBaseClass = "BaseEntity<string>";

    private readonly string _namespace;
    private readonly string _baseClass;

    public EntityGenerator(string targetNamespace, string baseClass = DefaultBaseClass)
    {
        _namespace = targetNamespace;
        _baseClass = baseClass;
    }

    private static void AppendAutoGeneratedHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by IntegratoR.CodeGen from D365 F&O $metadata.");
        sb.AppendLine("//     Do not modify — changes will be overwritten.");
        sb.AppendLine("// </auto-generated>");
    }

    /// <summary>
    /// Generates entity and enum source files into the specified output directory.
    /// Returns the number of files generated.
    /// </summary>
    public int Generate(CsdlSchema schema, string outputDir, HashSet<string>? entitySetFilter)
    {
        Directory.CreateDirectory(outputDir);
        int count = 0;

        // Collect enum types referenced by entities we'll generate
        var referencedEnums = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (ODataEntityModel entity in schema.EntityTypes)
        {
            if (!ShouldGenerate(entity, entitySetFilter)) continue;

            string code = GenerateEntity(entity);
            string filePath = Path.Combine(outputDir, $"{entity.Name}.g.cs");
            File.WriteAllText(filePath, code);
            count++;

            foreach (ODataPropertyModel prop in entity.Properties.Where(p => p.IsEnum && p.EnumTypeName is not null))
            {
                referencedEnums.Add(prop.EnumTypeName!);
            }
        }

        // Generate referenced enum types
        foreach (ODataEnumModel enumModel in schema.EnumTypes)
        {
            if (!referencedEnums.Contains(enumModel.Name)) continue;

            string code = GenerateEnum(enumModel);
            string filePath = Path.Combine(outputDir, $"{enumModel.Name}.g.cs");
            File.WriteAllText(filePath, code);
            count++;
        }

        return count;
    }

    private static bool ShouldGenerate(ODataEntityModel entity, HashSet<string>? entitySetFilter)
    {
        if (entitySetFilter is null) return entity.EntitySetName is not null;

        return entity.EntitySetName is not null &&
               (entitySetFilter.Contains(entity.EntitySetName) || entitySetFilter.Contains(entity.Name));
    }

    private string GenerateEntity(ODataEntityModel entity)
    {
        var sb = new StringBuilder();

        AppendAutoGeneratedHeader(sb);
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using IntegratoR.Abstractions.Domain.Entities;");
        sb.AppendLine("using IntegratoR.OData.Common.Annotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespace};");
        sb.AppendLine();

        if (entity.IsReadOnly)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Read-only D365 entity: {entity.Label ?? entity.Name}.");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine($"[Table(\"{entity.EntitySetName}\")]");
        sb.AppendLine($"public partial class {entity.Name} : {_baseClass}");
        sb.AppendLine("{");

        // Generate properties
        foreach (ODataPropertyModel prop in entity.Properties)
        {
            GenerateProperty(sb, prop);
        }

        // Generate GetCompositeKey
        sb.AppendLine("    /// <inheritdoc/>");
        sb.Append("    public override object[] GetCompositeKey() => [");

        var keyProps = entity.Properties.Where(p => p.IsKey).ToList();
        if (keyProps.Count > 0)
        {
            sb.Append(string.Join(", ", keyProps.Select(k => ToPascalCase(k.Name))));
        }

        sb.AppendLine("];");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateProperty(StringBuilder sb, ODataPropertyModel prop)
    {
        string csharpType = MapEdmType(prop);
        string pascalName = ToPascalCase(prop.Name);
        bool needsNullable = prop.IsNullable && !prop.IsEnum && IsReferenceType(csharpType);

        // Key attribute
        if (prop.IsKey)
        {
            sb.AppendLine("    [Key]");
        }

        // JsonPropertyName
        sb.AppendLine($"    [JsonPropertyName(\"{prop.Name}\")]");

        // ODataField attribute — only emit if there's something non-default to express
        string odataFieldArgs = BuildODataFieldArgs(prop);
        if (!string.IsNullOrEmpty(odataFieldArgs))
        {
            sb.AppendLine($"    [ODataField({odataFieldArgs})]");
        }

        // Property declaration: IsRequired or IsKey forces non-nullable
        bool effectivelyRequired = prop.IsKey || prop.IsRequired || !prop.IsNullable;
        string typeDecl = csharpType;
        if (!effectivelyRequired && !IsValueType(csharpType))
        {
            typeDecl = $"{csharpType}?";
        }
        else if (prop.IsNullable && !effectivelyRequired && IsValueType(csharpType))
        {
            typeDecl = $"{csharpType}?";
        }

        string requiredKeyword = effectivelyRequired ? "required " : "";

        sb.AppendLine($"    public {requiredKeyword}{typeDecl} {pascalName} {{ get; set; }}");
        sb.AppendLine();
    }

    private static string BuildODataFieldArgs(ODataPropertyModel prop)
    {
        var args = new List<string>();

        if (!prop.AllowEdit)
            args.Add("AllowEdit = false");
        if (!prop.AllowEditOnCreate)
            args.Add("AllowEditOnCreate = false");
        if (prop.IsRequired)
            args.Add("IsRequired = true");
        if (prop.EdmType is not null)
            args.Add($"EdmType = \"{prop.EdmType}\"");

        return string.Join(", ", args);
    }

    private string GenerateEnum(ODataEnumModel enumModel)
    {
        var sb = new StringBuilder();

        AppendAutoGeneratedHeader(sb);
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespace};");
        sb.AppendLine();
        sb.AppendLine($"public enum {enumModel.Name}");
        sb.AppendLine("{");

        for (int i = 0; i < enumModel.Members.Count; i++)
        {
            ODataEnumMember member = enumModel.Members[i];
            string comma = i < enumModel.Members.Count - 1 ? "," : "";
            sb.AppendLine($"    {SanitizeEnumMember(member.Name)} = {member.Value}{comma}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    internal static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (char.IsUpper(name[0])) return name;
        return char.ToUpper(name[0], CultureInfo.InvariantCulture) + name[1..];
    }

    private static string SanitizeEnumMember(string name)
    {
        // C# identifiers can't start with a digit or contain special chars
        return name.Replace("-", "_").Replace(" ", "_");
    }

    private static string MapEdmType(ODataPropertyModel prop)
    {
        if (prop.IsEnum && prop.EnumTypeName is not null)
            return prop.EnumTypeName;

        return prop.EdmType switch
        {
            "Edm.String" => "string",
            "Edm.Int32" => "int",
            "Edm.Int64" => "long",
            "Edm.Int16" => "short",
            "Edm.Decimal" => "decimal",
            "Edm.Double" => "double",
            "Edm.Single" => "float",
            "Edm.Boolean" => "bool",
            "Edm.DateTimeOffset" => "DateTimeOffset",
            "Edm.DateTime" => "DateTime",
            "Edm.Date" => "DateOnly",
            "Edm.TimeOfDay" => "TimeOnly",
            "Edm.Guid" => "Guid",
            "Edm.Byte" => "byte",
            "Edm.SByte" => "sbyte",
            "Edm.Binary" => "byte[]",
            _ => "object"
        };
    }

    private static bool IsValueType(string csharpType)
    {
        return csharpType is "int" or "long" or "short" or "decimal" or "double" or "float"
            or "bool" or "byte" or "sbyte" or "DateTimeOffset" or "DateTime"
            or "DateOnly" or "TimeOnly" or "Guid";
    }

    private static bool IsReferenceType(string csharpType)
    {
        return csharpType is "string" or "byte[]" or "object";
    }
}
