<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IntegratoR.Abstractions.Tests" />
  </ItemGroup>

</Project>
