<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IntegratoR.Abstractions\IntegratoR.Abstractions.csproj" />
    <ProjectReference Include="..\IntegratoR.OData\IntegratoR.OData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IntegratoR.Hosting" />
    <InternalsVisibleTo Include="IntegratoR.OData.FO.Tests" />
  </ItemGroup>

</Project>
