<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>integrator-codegen</ToolCommandName>
  </PropertyGroup>

  <!-- MSBuild task excluded until moved to separate IntegratoR.CodeGen.MSBuild project -->
  <ItemGroup>
    <Compile Remove="Tasks\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IntegratoR.CodeGen.Tests" />
  </ItemGroup>

</Project>
