namespace IntegratoR.OData.Common.Annotations;

/// <summary>
/// Provides declarative, property-level metadata to control serialization behavior
/// for D365 F&O OData create (POST) and update (PATCH) operations.
/// </summary>
/// <remarks>
/// This attribute is intended to be used on properties of the client-side entity models
/// that map to D365 F&O data entities.
///
/// A generic OData repository implementation would use reflection to inspect an entity's
/// properties before a create or update operation. It would check for this attribute and
/// dynamically build the request payload, excluding properties as configured. This keeps the
/// data access logic clean and reusable, while the entity models themselves define the serialization rules.
/// </remarks>
[AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
public class ODataFieldAttribute : Attribute
{
    /// <summary>
    /// Gets or sets a value indicating whether this property should be excluded from the
    /// payload of a 'Create' (POST) request.
    /// </summary>
    /// <remarks>
    /// This is ideal for fields that are server-generated by D365 F&O and should not be
    /// specified by the client on creation.
    /// <example>
    /// Example: A sales order number generated by a number sequence.
    /// <code>
    /// [ODataField(IgnoreOnCreate = true)]
    /// public string SalesOrderNumber { get; set; }
    /// </code>
    /// </example>
    /// </remarks>
    public bool IgnoreOnCreate { get; set; } = false;

    /// <summary>
    /// Gets or sets a value indicating whether this property should be excluded from the
    /// payload of an 'Update' (PATCH) request.
    /// </summary>
    /// <remarks>
    /// This is ideal for read-only fields or primary key fields that cannot be changed
    /// after the entity has been created.
    /// <example>
    /// Example: The customer account number on an existing customer record.
    /// <code>
    /// [ODataField(IgnoreOnUpdate = true)]
    /// public string CustomerAccount { get; set; }
    /// </code>
    /// </example>
    /// </remarks>
    public bool IgnoreOnUpdate { get; set; } = false;
}