namespace IntegratoR.OData.Common.Annotations;

/// <summary>
/// Provides declarative, property-level metadata to control serialization behavior
/// for D365 F&amp;O OData create (POST) and update (PATCH) operations.
/// </summary>
/// <remarks>
/// <para>
/// Properties from the D365 CSDL <c>$metadata</c> annotations drive the <see cref="AllowEdit"/> and
/// <see cref="AllowEditOnCreate"/> flags. When set, these are the <b>source of truth</b> from D365
/// and take precedence over <see cref="IgnoreOnCreate"/>/<see cref="IgnoreOnUpdate"/>.
/// </para>
/// <para>
/// For backward compatibility, hand-written entities can still use <see cref="IgnoreOnCreate"/> and
/// <see cref="IgnoreOnUpdate"/> directly. The effective exclusion logic is:
/// <list type="bullet">
///   <item>Exclude on create = <see cref="IgnoreOnCreate"/> OR <see cref="AllowEditOnCreate"/> == false</item>
///   <item>Exclude on update = <see cref="IgnoreOnUpdate"/> OR <see cref="AllowEdit"/> == false</item>
/// </list>
/// </para>
/// </remarks>
[AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
public class ODataFieldAttribute : Attribute
{
    /// <summary>
    /// Gets or sets a value indicating whether this property should be excluded from the
    /// payload of a 'Create' (POST) request.
    /// </summary>
    /// <remarks>
    /// This is ideal for fields that are server-generated by D365 F&amp;O and should not be
    /// specified by the client on creation.
    /// </remarks>
    public bool IgnoreOnCreate { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this property should be excluded from the
    /// payload of an 'Update' (PATCH) request.
    /// </summary>
    /// <remarks>
    /// This is ideal for read-only fields or primary key fields that cannot be changed
    /// after the entity has been created.
    /// </remarks>
    public bool IgnoreOnUpdate { get; set; }

    /// <summary>
    /// Gets or sets whether the field allows editing after creation.
    /// Maps to D365 CSDL annotation <c>Microsoft.Dynamics.OData.Core.V1.AllowEdit</c>.
    /// When <c>false</c>, the field is excluded from update (PATCH) payloads.
    /// Defaults to <c>true</c>.
    /// </summary>
    public bool AllowEdit { get; set; } = true;

    /// <summary>
    /// Gets or sets whether the field allows editing on create.
    /// Maps to D365 CSDL annotation <c>Microsoft.Dynamics.OData.Core.V1.AllowEditOnCreate</c>.
    /// When <c>false</c>, the field is excluded from create (POST) payloads.
    /// Defaults to <c>true</c>.
    /// </summary>
    public bool AllowEditOnCreate { get; set; } = true;

    /// <summary>
    /// Gets or sets whether the field is required (non-nullable) in D365.
    /// Maps to D365 CSDL annotation <c>Microsoft.Dynamics.OData.Core.V1.IsRequired</c>
    /// and/or <c>Nullable="false"</c> on the CSDL property.
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Gets or sets the OData EDM type of the property (e.g., <c>"Edm.String"</c>, <c>"Edm.Int32"</c>).
    /// Maps to the <c>Type</c> attribute on the CSDL <c>&lt;Property&gt;</c> element.
    /// Informational — used by the code generator for diagnostics.
    /// </summary>
    public string? EdmType { get; set; }

    /// <summary>
    /// Gets or sets the D365 label reference (e.g., <c>"@SYS13342"</c>).
    /// Maps to D365 CSDL annotation <c>Microsoft.Dynamics.OData.Core.V1.LabelId</c>.
    /// Informational — used for documentation purposes.
    /// </summary>
    public string? Label { get; set; }

    /// <summary>
    /// Gets the effective exclusion flag for create operations.
    /// A property is excluded from create payloads if <see cref="IgnoreOnCreate"/> is <c>true</c>
    /// OR <see cref="AllowEditOnCreate"/> is <c>false</c>.
    /// </summary>
    public bool EffectiveIgnoreOnCreate => IgnoreOnCreate || !AllowEditOnCreate;

    /// <summary>
    /// Gets the effective exclusion flag for update operations.
    /// A property is excluded from update payloads if <see cref="IgnoreOnUpdate"/> is <c>true</c>
    /// OR <see cref="AllowEdit"/> is <c>false</c>.
    /// </summary>
    public bool EffectiveIgnoreOnUpdate => IgnoreOnUpdate || !AllowEdit;
}
