<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentResults" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IntegratoR.Abstractions\IntegratoR.Abstractions.csproj" />
    <ProjectReference Include="..\..\IntegratoR.OData\IntegratoR.OData.csproj" />
  </ItemGroup>

</Project>
